import { z } from 'zod';
import type { DeskState } from './deskState.ts';

export const DESK_MODES = ['worktree', 'shared'] as const;
export type DeskMode = (typeof DESK_MODES)[number];

export const PERMISSION_MODES = ['default', 'acceptEdits', 'auto', 'plan', 'bypassPermissions'] as const;
export type PermissionMode = (typeof PERMISSION_MODES)[number];

export interface Room {
  id: string;
  name: string;
  projectPath: string;
  isGitRepo: boolean;
  accentColor: string;
  position: number;
  createdAt: number;
}

export interface Desk {
  id: string;
  roomId: string;
  name: string;
  slug: string;
  mode: DeskMode;
  workdir: string;
  branch: string | null;
  sessionId: string;
  model: string | null;
  permissionMode: PermissionMode | null;
  /** Seed used to generate the character's appearance. */
  appearanceSeed: number;
  position: number;
  state: DeskState;
  stateSince: number;
  /** What the desk is working on: declared through the office MCP, or the last prompt. */
  currentTask: string | null;
  /** Conversation title generated by Claude Code (e.g. "Add subtract function"). */
  sessionTitle: string | null;
  /** Tool currently in use, e.g. "Edit" — only meaningful while working. */
  currentTool: string | null;
  lastPrompt: string | null;
  lastAssistantMessage: string | null;
  createdAt: number;
}

export const createRoomSchema = z.object({
  name: z.string().trim().min(1).max(80),
  projectPath: z.string().trim().min(1),
  accentColor: z
    .string()
    .regex(/^#[0-9a-fA-F]{6}$/)
    .optional(),
});
export type CreateRoomInput = z.infer<typeof createRoomSchema>;

export const updateRoomSchema = z.object({
  name: z.string().trim().min(1).max(80).optional(),
  accentColor: z
    .string()
    .regex(/^#[0-9a-fA-F]{6}$/)
    .optional(),
});
export type UpdateRoomInput = z.infer<typeof updateRoomSchema>;

export const createDeskSchema = z.object({
  roomId: z.string().min(1),
  name: z.string().trim().min(1).max(40).optional(),
  mode: z.enum(DESK_MODES).default('worktree'),
  model: z.string().trim().min(1).max(60).optional(),
  permissionMode: z.enum(PERMISSION_MODES).optional(),
  initialPrompt: z.string().trim().min(1).max(20_000).optional(),
});
export type CreateDeskInput = z.infer<typeof createDeskSchema>;

export const updateDeskSchema = z.object({
  name: z.string().trim().min(1).max(40).optional(),
});
export type UpdateDeskInput = z.infer<typeof updateDeskSchema>;

export const loginSchema = z.object({
  password: z.string().min(1).max(512),
});
