import { z } from 'zod';
import type { DeskState } from './deskState.ts';

export const DESK_MODES = ['worktree', 'shared'] as const;
export type DeskMode = (typeof DESK_MODES)[number];

export const PERMISSION_MODES = ['default', 'acceptEdits', 'auto', 'plan', 'bypassPermissions'] as const;
export type PermissionMode = (typeof PERMISSION_MODES)[number];

export const ATTENTION_KINDS = [
  'question',
  'permission',
  'plan',
  'message',
  'error',
  'limit',
  'trust',
] as const;
export type AttentionKind = (typeof ATTENTION_KINDS)[number];

/** What a desk is waiting for from the human, when it is waiting. */
export interface DeskAttention {
  kind: AttentionKind;
  /** Content from the session (question asked, command to approve, error…), may be empty. */
  text: string;
}

export interface Room {
  id: string;
  name: string;
  projectPath: string;
  isGitRepo: boolean;
  accentColor: string;
  position: number;
  createdAt: number;
}

export interface Desk {
  id: string;
  roomId: string;
  name: string;
  slug: string;
  mode: DeskMode;
  workdir: string;
  branch: string | null;
  sessionId: string;
  model: string | null;
  permissionMode: PermissionMode | null;
  /** Seed used to generate the character's appearance. */
  appearanceSeed: number;
  position: number;
  state: DeskState;
  stateSince: number;
  /** What the desk is working on: declared through the office MCP, or the last prompt. */
  currentTask: string | null;
  /** Conversation title generated by Claude Code (e.g. "Add subtract function"). */
  sessionTitle: string | null;
  /** Tool currently in use, e.g. "Edit" — only meaningful while working. */
  currentTool: string | null;
  lastPrompt: string | null;
  lastAssistantMessage: string | null;
  attention: DeskAttention | null;
  createdAt: number;
}

export type SummaryStatus = 'idle' | 'generating' | 'error';

/** The Haiku-written summary shown in the master office. */
export interface OfficeSummary {
  status: SummaryStatus;
  text: string | null;
  language: string | null;
  generatedAt: number | null;
  /** Start of the period the summary covers (the previous visit). */
  since: number | null;
  error: string | null;
}

export interface RoomMessage {
  id: number;
  roomId: string;
  /** Sender desk, or null when the human wrote it. */
  fromDeskId: string | null;
  /** Recipient desk, or null for the whole room. */
  toDeskId: string | null;
  body: string;
  createdAt: number;
}

export interface RoomNote {
  id: number;
  roomId: string;
  /** Author desk, or null when the human pinned it. */
  deskId: string | null;
  body: string;
  createdAt: number;
}

/** Shared state of a room, seen by its desks (through the office MCP) and drawn on its whiteboard. */
export interface RoomBoard {
  roomId: string;
  notes: RoomNote[];
  /** Most recent messages, oldest first. */
  messages: RoomMessage[];
}

export const postRoomMessageSchema = z.object({
  body: z.string().trim().min(1).max(4000),
  toDeskId: z.string().min(1).nullable().optional(),
});

export const postRoomNoteSchema = z.object({
  body: z.string().trim().min(1).max(1000),
});

export const createRoomSchema = z.object({
  name: z.string().trim().min(1).max(80),
  projectPath: z.string().trim().min(1),
  accentColor: z
    .string()
    .regex(/^#[0-9a-fA-F]{6}$/)
    .optional(),
});
export type CreateRoomInput = z.infer<typeof createRoomSchema>;

export const updateRoomSchema = z.object({
  name: z.string().trim().min(1).max(80).optional(),
  accentColor: z
    .string()
    .regex(/^#[0-9a-fA-F]{6}$/)
    .optional(),
});
export type UpdateRoomInput = z.infer<typeof updateRoomSchema>;

export const createDeskSchema = z.object({
  roomId: z.string().min(1),
  name: z.string().trim().min(1).max(40).optional(),
  mode: z.enum(DESK_MODES).default('worktree'),
  model: z.string().trim().min(1).max(60).optional(),
  permissionMode: z.enum(PERMISSION_MODES).optional(),
  initialPrompt: z.string().trim().min(1).max(20_000).optional(),
});
export type CreateDeskInput = z.infer<typeof createDeskSchema>;

export const updateDeskSchema = z.object({
  name: z.string().trim().min(1).max(40).optional(),
});
export type UpdateDeskInput = z.infer<typeof updateDeskSchema>;

export interface TimelineSegment {
  state: DeskState;
  from: number;
  to: number;
}

export interface DeskTimeline {
  deskId: string;
  segments: TimelineSegment[];
  /** Timestamps of the prompts the desk received. */
  prompts: number[];
}

export interface Timeline {
  from: number;
  to: number;
  desks: DeskTimeline[];
}

export const summaryRequestSchema = z.object({
  reason: z.enum(['visit', 'refresh']),
  language: z.enum(['fr', 'en']),
});

export const loginSchema = z.object({
  password: z.string().min(1).max(512),
});
